// <auto-generated />
namespace LifeAssure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixedCustomerPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedCustomerPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "202111232318598_FixedCustomerPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
